### ISSUE TITLE
[Feature Request] Parse the `workspace` field

### ISSUE THREAD

**Issue by July541** [benesch/cargo-manifmt#3]
Currently, manifmt haven't deal with workspace filed like:
```toml
[workspace]
resolver = "2"
members = [
  "foo",
  "aaa/bar"
]
```

It will delete all workspace yet now.

I tried to implement this and was obstructed by [`WorkspaceRootConfig`](https://docs.rs/cargo/0.59.0/cargo/core/struct.WorkspaceRootConfig.html#impl) doesn't expose any public method to access, I'm not sure I'm in the right position.
